// Hardcoded POIs per Tokyo ward — used for the SVG fallback map and when the
// Google Places API is unavailable or returns nothing.
export const locationMarkers = {
  Shibuya: [
    {
      id: 'shibuya-shelter',
      category: 'shelter',
      name: 'Miyashita Park Shelter',
      shortName: 'Miyashita Park',
      shortNameJa: '宮下公園',
      shortNameZh: '宫下公园',
      shortNameVi: 'Công viên Miyashita',
      distance: '400m',
      detailDesc: 'Open, elevated shelter, 400m, ADA compliant path available',
      x: 252, y: 345,
      lat: 35.6617, lng: 139.7020,
      desc: 'Elevated open-air park. Capacity: 5,000. ADA Access verified.'
    },
    {
      id: 'shibuya-shelter-2',
      category: 'shelter',
      name: 'Yoyogi Gym Refuge',
      shortName: 'Yoyogi Gym',
      shortNameJa: '代々木体育館',
      shortNameZh: '代代木体育馆',
      shortNameVi: 'Nhà thi đấu Yoyogi',
      distance: '750m',
      detailDesc: 'Indoor heavy structure, 750m',
      x: 50, y: 150,
      lat: 35.6631, lng: 139.6975,
      desc: 'Reinforced seismic dome structure. Capacity: 10,000.'
    },
    {
      id: 'shibuya-shelter-3',
      category: 'shelter',
      name: 'Jingu-mae Shelter',
      shortName: 'Jingu-mae Shelter',
      shortNameJa: '神宮前避難所',
      shortNameZh: '神宫前避难所',
      shortNameVi: 'Khu trú ẩn Jingu-mae',
      distance: '620m',
      detailDesc: 'Outdoor park space, 620m',
      x: 310, y: 450,
      lat: 35.6590, lng: 139.7060,
      desc: 'Local community assembly ground. Basic emergency kit.'
    },
    { id: 'shibuya-water', category: 'water', name: 'Shibuya Well Station', x: 120, y: 320, lat: 35.6585, lng: 139.6975, desc: 'Solar-powered ground aquifer water tap. Active.' },
    { id: 'shibuya-water-2', category: 'water', name: 'South Shibuya Supply Gate', x: 200, y: 600, lat: 35.6545, lng: 139.7010, desc: 'Backup underground municipal water cistern. High volume.' },
    { id: 'shibuya-water-3', category: 'water', name: 'Harajuku Reservoir Node', x: 80, y: 220, lat: 35.6610, lng: 139.6950, desc: 'Clean gravity-fed fresh-water distribution post.' },
    { id: 'shibuya-medical', category: 'medical', name: 'Shibuya Triage Center', x: 280, y: 550, lat: 35.6558, lng: 139.7040, desc: 'First aid, blankets, and local network routing.' },
    { id: 'shibuya-medical-2', category: 'medical', name: 'Shibuya West Clinic Outpost', x: 160, y: 380, lat: 35.6598, lng: 139.6990, desc: 'Volunteer physician group. Wound care & basic triage.' },
    { id: 'shibuya-hazard', category: 'hazard', name: 'Fallen Glass Hazard', x: 100, y: 450, lat: 35.6575, lng: 139.6995, desc: 'Shattered facade glass. Blocked road.' },
    { id: 'shibuya-hazard-2', category: 'hazard', name: 'Fallen Signage Blockage', x: 220, y: 280, lat: 35.6630, lng: 139.7035, desc: 'Commercial steel sign fallen across pedestrian path.' }
  ],
  Minato: [
    {
      id: 'minato-shelter',
      category: 'shelter',
      name: 'Shiba Park Shelter',
      shortName: 'Shiba Park',
      shortNameJa: '芝公園',
      shortNameZh: '芝公园',
      shortNameVi: 'Công viên Shiba',
      distance: '650m',
      detailDesc: 'Open, 650m',
      x: 210, y: 390,
      lat: 35.6556, lng: 139.7483,
      desc: 'Large open-ground shelter near Tokyo Tower. Capacity: 8,000.'
    },
    {
      id: 'minato-shelter-2',
      category: 'shelter',
      name: 'Akasaka Sacas Refuge',
      shortName: 'Akasaka Sacas',
      shortNameJa: '赤坂サカス',
      shortNameZh: '赤坂Sacas',
      shortNameVi: 'Refuge Akasaka Sacas',
      distance: '900m',
      detailDesc: 'High concrete plaza, 900m',
      x: 80, y: 480,
      lat: 35.6580, lng: 139.7350,
      desc: 'High-elevation open concrete square. Tsunami resilient.'
    },
    {
      id: 'minato-shelter-3',
      category: 'shelter',
      name: 'Sports Center Refuge',
      shortName: 'Sports Center',
      shortNameJa: '港区スポーツセンター',
      shortNameZh: '港区体育中心',
      shortNameVi: 'Trung tâm Thể thao',
      distance: '1.2km',
      detailDesc: 'Indoor shelter, 1.2km',
      x: 320, y: 320,
      lat: 35.6515, lng: 139.7540,
      desc: 'Emergency backup food, blankets, and blankets warehouse.'
    },
    { id: 'minato-water', category: 'water', name: 'Tokyo Tower Water Reservoir', x: 100, y: 250, lat: 35.6586, lng: 139.7454, desc: 'Underground emergency fresh-water supply.' },
    { id: 'minato-water-2', category: 'water', name: 'Mita Water Reserve Gate', x: 260, y: 580, lat: 35.6495, lng: 139.7480, desc: 'Automated high-capacity groundwater pumping station.' },
    { id: 'minato-water-3', category: 'water', name: 'Roppongi Hills Water Point', x: 150, y: 420, lat: 35.6540, lng: 139.7410, desc: 'Earthquake-safe storage reservoir with manual distribution lines.' },
    { id: 'minato-medical', category: 'medical', name: 'Roppongi Medical Clinic', x: 290, y: 520, lat: 35.6620, lng: 139.7330, desc: 'Triage team active. Emergency generator operational.' },
    { id: 'minato-medical-2', category: 'medical', name: 'Toranomon First Aid Outpost', x: 180, y: 300, lat: 35.6595, lng: 139.7440, desc: 'Red Cross disaster caravan. Clean bandages and sutures.' },
    { id: 'minato-hazard', category: 'hazard', name: 'Structural Risk: Overpass', x: 150, y: 580, lat: 35.6530, lng: 139.7420, desc: 'Highway structural cracks. High risk area.' },
    { id: 'minato-hazard-2', category: 'hazard', name: 'Fallen Concrete Panel', x: 230, y: 200, lat: 35.6610, lng: 139.7490, desc: 'Masonry facade panel fallen onto active vehicle lane.' }
  ],
  Shinjuku: [
    {
      id: 'shinjuku-shelter',
      category: 'shelter',
      name: 'Shinjuku Gyoen Shelter',
      shortName: 'Shinjuku Gyoen',
      shortNameJa: '新宿御苑',
      shortNameZh: '新宿御苑',
      shortNameVi: 'Công viên Shinjuku Gyoen',
      distance: '800m',
      detailDesc: 'Open, 800m',
      x: 250, y: 490,
      lat: 35.6852, lng: 139.7095,
      desc: 'Massive open park refuge. Capacity: 25,000. Windbreak forest.'
    },
    {
      id: 'shinjuku-shelter-2',
      category: 'shelter',
      name: 'Shinjuku Chuo Park',
      shortName: 'Chuo Park',
      shortNameJa: '新宿中央公園',
      shortNameZh: '新宿中央公园',
      shortNameVi: 'Công viên Shinjuku Chuo',
      distance: '950m',
      detailDesc: 'Open park, 950m',
      x: 120, y: 220,
      lat: 35.6945, lng: 139.6910,
      desc: 'Multi-level open park. Hydrant connections and local radio.'
    },
    {
      id: 'shinjuku-shelter-3',
      category: 'shelter',
      name: 'Toyama Park Shelter',
      shortName: 'Toyama Park',
      shortNameJa: '戸山公園',
      shortNameZh: '户山公园',
      shortNameVi: 'Công viên Toyama',
      distance: '1.4km',
      detailDesc: 'Wooded park, 1.4km',
      x: 340, y: 400,
      lat: 35.7010, lng: 139.7150,
      desc: 'Hilly open-space refuge area. Stocked water storage.'
    },
    { id: 'shinjuku-water', category: 'water', name: 'Gyoen Water Station', x: 300, y: 310, lat: 35.6880, lng: 139.7130, desc: 'Clean groundwater well with manual pumps.' },
    { id: 'shinjuku-water-2', category: 'water', name: 'West Shinjuku Supply Node', x: 80, y: 480, lat: 35.6870, lng: 139.6890, desc: 'Solar-powered smart municipal water tap station.' },
    { id: 'shinjuku-water-3', category: 'water', name: 'Kabukicho Well Station', x: 190, y: 150, lat: 35.6960, lng: 139.7010, desc: 'Deep-aquifer borehole well. Active under local generator power.' },
    { id: 'shinjuku-medical', category: 'medical', name: 'Shinjuku First Aid Tent', x: 110, y: 420, lat: 35.6895, lng: 139.6990, desc: 'Red Cross outpost. Medical supplies stocked.' },
    { id: 'shinjuku-medical-2', category: 'medical', name: 'Gyoen Gate Triage Station', x: 240, y: 580, lat: 35.6840, lng: 139.7110, desc: 'Mobile first aid clinic stationed near the Gyoen entrance.' },
    { id: 'shinjuku-hazard', category: 'hazard', name: 'Subway Flooding', x: 190, y: 200, lat: 35.6905, lng: 139.7040, desc: 'Underground tunnel ingress. Closed.' },
    { id: 'shinjuku-hazard-2', category: 'hazard', name: 'Gyoen Perimeter Slope Failure', x: 280, y: 450, lat: 35.6865, lng: 139.7125, desc: 'Slope landslide risk. Retaining brick wall collapsed.' }
  ]
};
